@startuml

' *** controlers ***
class UserController{
+niewueUser()
+getUser()
}

class BelastingController{
+NieuweInkomenBelasting()
}

'-----------------



' *** Services ***
class UserService{
+niewueUser()
+GetUser()
+BestaatAlEmail()
}

class BelastingService{
+NieuweInkomenBelastingToevoegen()
-nieuweBelastingmaken()
+BestaatAlInkomenBelasting
}

'*** package belastingbereken ***
interface Belastingbereken{
berekenen()
}

class Inkomenbelastingberekenen{
berekenen()
}
'-----------------



' *** models ***
interface User{
+id
+name
+email
+password
+isAdmin

}

class Admin{
}

class GewoneUser{
  -belastingenPerJaar:Map<Integer,List<Belasting>>

  +nieuweBelastingMetJaar()
  +getBelastingListMetJaar()
  +setBelastingToevoegen()

}

class Belasting{
 -userid;
 -belastingsoort;
 -belastingJaar;
 -inkomem;
 -belastingBedrag;
}

'-----------------


' *** DataBase ***
package DataBase{}

' *** Relations ***
User--|>GewoneUser
User--|>Admin

GewoneUser "1" -- "1..*" Belasting : bevat

UserController-->UserService
BelastingController-->BelastingService

UserService..>User
BelastingService..>Belasting

Belastingbereken..|>Inkomenbelastingberekenen
BelastingService-->Belastingbereken

UserService-->DataBase
BelastingService-->DataBase

@enduml